Name:           ros-indigo-rb1-base-description
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS rb1_base_description package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rb1_base_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-robotnik-sensors
Requires:       ros-indigo-urdf
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-robotnik-sensors
BuildRequires:  ros-indigo-roslaunch
BuildRequires:  ros-indigo-urdf
BuildRequires:  ros-indigo-xacro

%description
The rb1_base_description package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jul 07 2016 Roberto Guzmán <rguzman@robotnik.es> - 1.0.3-0
- Autogenerated by Bloom

* Wed Jul 06 2016 Roberto Guzmán <rguzman@robotnik.es> - 1.0.2-0
- Autogenerated by Bloom

